### ISSUE TITLE
Reporting: Default to most recent service (or first)

### ISSUE THREAD

**Issue by phorne-uncharted** [microsoft/community-organization-operations-suite#293]
When on the reporting page selecting services, the system should default to the most recently viewed service (by that user). If no service has been viewed by that user, then the system should default to the first service listed.

![image](https://user-images.githubusercontent.com/20339669/152595017-37743f57-842b-46a6-baaf-ab98ff9852f2.png)

**Comment by ThomasKapler** [comment]
Not resolved on staging...
