### ISSUE TITLE
Replace Tag Pulldown Select Filter With Table Column Filter

### ISSUE THREAD

**Issue by phorne-uncharted** [microsoft/community-organization-operations-suite#294]
On the Tags page, the pulldown select filter should be removed. Instead, The tag listing table should allow the user to filter by tag.

![image](https://user-images.githubusercontent.com/20339669/152597536-9cd444c0-a929-4148-9c24-af6bec15431b.png)

**Comment by YohannParis** [comment]
A la place de simplement amener la fonction de filtrage, commence a utiliser le nouveau composent Detail list, see #309
