### ISSUE TITLE
Persist Displayed Fields

### ISSUE THREAD

**Issue by phorne-uncharted** [microsoft/community-organization-operations-suite#295]
In the reporting page, the displayed fields for a given table should be persisted on a per user basis. Whenever the user navigates back to the reporting page and selects a report they had previously selected, the previous list of displayed fields needs to be used when building the table. Whenever the user updates the list of displayed fields, the updated list should be remembered so that it can be used the next time the user navigates to the same table. The list of fields to display selected by one user should not impact the list of fields to display for another user.

The system needs to remember the field list even if the user logs out or shuts down the system.

![image](https://user-images.githubusercontent.com/20339669/152600194-d8102177-a4f6-4523-9bc3-7bbdb4a7ce5e.png)

**Comment by YohannParis** [comment]
Start by looking at #333 which includes how the API parts of saving user preferences was done.
