### ISSUE TITLE
Persist Selected Filters

### ISSUE THREAD

**Issue by phorne-uncharted** [microsoft/community-organization-operations-suite#296]
In the reporting page, the selected filters for a given table should be persisted on a per user basis. Whenever the user navigates back to the reporting page and selects a report they had previously selected, the previous list of filters needs to be used when building the table. Whenever the user updates the list of filters, the updated list should be remembered so that it can be used the next time the user navigates to the same table. The list of filters selected by one user should not impact the list of filters for another user.

The system needs to remember the filter list even if the user logs out or shuts down the system.

**Comment by YohannParis** [comment]
Start by looking at #333 which includes how the API parts of saving user preferences was done.
