### ISSUE TITLE
Cant use same email on two different environments

### ISSUE THREAD

**Issue by danielfe** [microsoft/community-organization-operations-suite#306]
Summary: It won’t let me create an account on demo if I use that email on prod. 

Steps to reproduce:
- Create an account on production (I actually have one on prod with a real CBO, I use dfeld@icloud.com)
- Log in to demo (you can use dfeld@me.com / worHem-pogsy9-sigpir if you want)
- Go to Specialists
- Click Add Specialist
- Fill out the info for the new person you want. Use the same email address you have on production. 

Results:
Expected - it lets me create the account in demo since I havent used that email yet
Actual - Nothing happens, but in console I see an error about using the same email (see screenshot). 

Note:
I’m not sure if this is a feature or a bug! What do you think? Maybe we shouldn’t allow the same email on two environments. Maybe instead we just fix the “+” issue and force folks to use a “+” in their email so they are clear which one is demo and which is production?

<img width="1440" alt="PastedGraphic-4" src="https://user-images.githubusercontent.com/4665144/153675988-aa720ebd-f113-461c-ae93-42bd36173ce4.png">

**Comment by phorne-uncharted** [comment]
This was due to the email already being used when accounts were initially created. However, in discussing this issue, a separate feature was noted as being required: being able to switch organization for users that are part of multiple organizations. A separate issue should be created to handle the new feature.
