### ISSUE TITLE
Tables: Long single words don't wrap

### ISSUE THREAD

**Issue by danielfe** [microsoft/community-organization-operations-suite#311]
In a table if we have a word that is longer than the space it is given (for example, a request title) it will overflow into the next column. We should consider an ellipsis or wrapping in this case. 

![image](https://user-images.githubusercontent.com/4665144/153915013-6238ac7e-0241-4e3e-8320-ed4f53954733.png)

**Comment by YohannParis** [comment]
@danielfe I'm havving issue reproducing this issue.

this is what I get on Firefox, Chrome, Edge, and Safari on macOS:
![Screen Shot 2022-03-10 at 11 13 29](https://user-images.githubusercontent.com/636801/157706271-0e621d57-80d9-4e29-b0af-cf9d394e6c2f.png)

**Comment by danielfe** [comment]
@YohannParis I think you are not reproducing because there are spaces in your test title. This bug is for very long words with no spaces. I just reproduced. 

I think this is kind of an edge case. A nice thing to improve but because it only happens when you dont use spaces, kind of an edge case

![image](https://user-images.githubusercontent.com/4665144/157729467-530dbf3e-e177-4ffb-ba4c-7b4e4ff1f819.png)
