### ISSUE TITLE
Dashboard - Waiting for Requests to load block the quick actions

### ISSUE THREAD

**Issue by YohannParis** [microsoft/community-organization-operations-suite#342]
While the dashboard is waiting to be loaded with _Requests_ the quick action panels are not rendered/usable.

https://user-images.githubusercontent.com/636801/154303938-b37581ee-5066-4cff-9fb5-a6067dd4391b.mov

**Comment by jryu01** [comment]
https://user-images.githubusercontent.com/3279838/160483218-39865a24-bc31-4255-b876-2312f52ba03b.mov

It doesn't look like a bug. As you can see from the recording, the side panel is populated before requests are loaded.
Since the service side panel is rendered with data fetched asynchronously, with slow network connection, it could take some time to get populated.

**Comment by YohannParis** [comment]
@jryu01 it is still a bug, the button should be disabled until the panel can be fully loaded, clicking on a button that does nothing is a poor user experience.
My point is the buttons can be priorotized to load before the rest.
Anyway, UI action should not be possible if not fully functional.

**Comment by jryu01** [comment]
The content of the `Start a Service` panel isn't static nor it's dependent on the data loaded on the main page. Once you open the side panel (by clicking the button), it starts to fetch the data from the backend and populate the panel. I think proper approach would be displaying a loading wheel in the panel to indicate that data is loading if we want to have a better UI.

**Comment by YohannParis** [comment]
At the end it's your issue, you can solve it as you see fit, and let @ThomasKapler make the final UX decision.

**Comment by jryu01** [comment]
Closing the issue since this issue can be addressed with https://github.com/microsoft/community-organization-operations-suite/issues/479
