### ISSUE TITLE
New Request form cannot be submitted unless the "optional" description is filled in

### ISSUE THREAD

**Issue by ThomasKapler** [microsoft/community-organization-operations-suite#369]
New Request form cannot be submitted unless the "optional" description is filled in. This means that the description is not really optional.

![image](https://user-images.githubusercontent.com/98921014/156199950-c20c8ad2-e7f8-46ec-9569-2dbc96121b55.png)

**Comment by ThomasKapler** [comment]
@danielfe I'm thinking this should be hi-priority as is slows down the user workflow... it forces them to enter a description, even if they don't want to. I think it will also be an easy fix

**Comment by danielfe** [comment]
thanks for the note! bumped up the priority.

**Comment by ThomasKapler** [comment]
Yohann, I think the description field IS SUPPOSED to be optional... Isn't that what Daniel said? I which case the fix should be that not having a description should not impact whether the "Create Request" button is active or not... 
@danielfe can you confirm?

**Comment by danielfe** [comment]
Yeah I think it should probably actually be optional. In some cases title is enough for chws i think
