### ISSUE TITLE
Re-assigning a request from yourself to someone else does not save

### ISSUE THREAD

**Issue by ThomasKapler** [microsoft/community-organization-operations-suite#375]
When I edit a request, change the specialist and then save, the change does not appear to get persisted. This occurred on integ version. Did not test production.

**Comment by danielfe** [comment]
I was able to reproduce this morning on demo, which I believe matches production

**Comment by danielfe** [comment]
Seems to reproduce every time for me on Chrome. Even refreshing browser window and after logging out and in. 

Here's a video, let me know if im doing something differently than you
https://www.loom.com/share/fe0c92ff5e02490a883c003b435f2042

**Comment by danielfe** [comment]
Yep, I can reproduce that. If it's not assigned to me and I change it, it appears to save the change correctly.

**Comment by karlolsonuc** [comment]
Yeah, getting repro even on local, debugging to see what's going wrong here.

**Comment by karlolsonuc** [comment]
Somehow didn't get closed after #466 was merged back. Double checked it's still fixed and it is, so closed.
