### ISSUE TITLE
redundant message when username or password are incorrect

### ISSUE THREAD

**Issue by ThomasKapler** [microsoft/community-organization-operations-suite#377]
When an incorrect username/password combination is entered, 2 error messages appear in login page

"Invalid email or password. Please try again."
"The email address or password you entered is incorrect. Please try again."

I suggest we only show the first one.

![image](https://user-images.githubusercontent.com/98921014/156623140-8d93c2be-f39d-43f5-a776-4cb1a4f2d973.png)

**Comment by danielfe** [comment]
The second string is better. But let's make sure there is only one.
