### ISSUE TITLE
Work with no or low internet - Requirements

### ISSUE THREAD

**Issue by danielfe** [microsoft/community-organization-operations-suite#380]
This is a theme area with a bit of research and some design needed. HCH should work well in situations where internet connectivity is not availability or reception is very poor.

**Comment by DChen602** [comment]
We're already planning an integration with the MSR Eng work for offline support.

**Comment by danielfe** [comment]
Awesome. Is there a ticket covering that we can dup this one to?

**Comment by danielfe** [comment]
Duplicate of #407 , closing.

**Comment by danielfe** [comment]
Kathey opened #407 to track this issue so I am closing this one.
