### ISSUE TITLE
Set up Staging branch and "Testing" server

### ISSUE THREAD

**Issue by ThomasKapler** [microsoft/community-organization-operations-suite#387]
As discussed, and new "staging" branch and "test?" server to allow testing against the completed sprint versions separate from dev and production.

![image](https://user-images.githubusercontent.com/98921014/156645868-cc09cc04-4b52-4793-8055-88f70a819e68.png)

I believe Chris Trevino needs to do this

**Comment by phorne-uncharted** [comment]
Done previously
