### ISSUE TITLE
Show Notes field in the client reporting table

### ISSUE THREAD

**Issue by danielfe** [microsoft/community-organization-operations-suite#397]
Now that there is a Notes field on Clients (#326) we should make sure this field can be shown in any reporting tables on Clients AND make sure it's exportable. Let's hide the column by default, but ensure that it can be shown by the user. (Support for hiding columns by default is in #396)

![image](https://user-images.githubusercontent.com/4665144/156835972-c59b2872-39cd-4f19-9cad-d77b9a0fa3d5.png)

**Comment by ThomasKapler** [comment]
Notes label does not appear in fields list or top of table column

**Comment by jonmarcello** [comment]
> Notes label does not appear in fields list or top of table column

The code has not yet been pushed to demo, closing this issue.
