### ISSUE TITLE
Add warning when specialist with email exists

### ISSUE THREAD

**Issue by ThomasKapler** [microsoft/community-organization-operations-suite#418]
When I try to "create specialist" nothing happens. It seems that creating specialist with the same email is not allowed, but there is no warning or message that this is the problem, so it just looks like its freezing up.

Need to add a popup warning that says "Email is used by another specialist <put name of specialist here>. Provide a different email address"

![image](https://user-images.githubusercontent.com/98921014/157499230-b33a568c-bab0-41dc-b329-03c4eea5e749.png)

**Comment by ThomasKapler** [comment]
After refreshing it seems to be working again. I do not know how to reproduce what I saw... Need to keep an eye on this.

**Comment by danielfe** [comment]
Proposed design: keep it simple and make it look like the rest of our form validation. I intentionally kept the string vague as to whether the email is used in this CBO or another. In the future we can allow users to be in more than one CBO but I think this fixes the silent failure for now. 

![image](https://user-images.githubusercontent.com/4665144/160907002-25a65423-d2fd-4f55-b418-053aca45900f.png)
