### ISSUE TITLE
Date of Birth chooser should default to show decades instead of current year 

### ISSUE THREAD

**Issue by ThomasKapler** [microsoft/community-organization-operations-suite#419]
Currently the DOB picker in New Clients shows current month on left and current year in months on the right.
![image](https://user-images.githubusercontent.com/98921014/157503031-a24ee245-3823-435a-b017-64b2d06a6195.png)

This is inconvenient because user probably needs to go back a couple of decades. So the right side should default to show decades.... like this
![image](https://user-images.githubusercontent.com/98921014/157503256-c9e17df1-b5d8-4e26-9fcb-146349b06195.png)

**Comment by danielfe** [comment]
When a date field is added to a service let's default that one to showing months, not years. ie keep that one the same. This is only for DOB.
