### ISSUE TITLE
Emails (like password reset) come from outdated name and email address

### ISSUE THREAD

**Issue by danielfe** [microsoft/community-organization-operations-suite#422]
SUMMARY
When you reset your password the email sender is "Resolve" and the from email is help@curamericas.org. It should be "Healthy Community Hub" and help@healthycommunityhub.com

STEPS TO REPRODUCE
- on log in page click forgot password
- enter your email
- Look for the email that comes in and check the sender

RESULTS
Sender is using a not out of date email and name

ENVIRONMENT
have reproduced on staging and demo

SCREENSHOTS
![image](https://user-images.githubusercontent.com/4665144/157722463-8c380150-410e-4500-8d65-6d4bf0524151.png)

**Comment by jryu01** [comment]
I believe this doesn't require the change in the codebase. 
We need to 
1. Change the email config in the environment configuration for each environment which can be done in Azure Portal
2. Add the new email address / domain in the sender whitelist in the sendgrid (3rd party email service provider) account for staging/demo/prod. (If not already done)

@phorne-uncharted I wonder if we have the access to sendgrid account used for prod/demo environments if we need to update the sender whitelist
