### ISSUE TITLE
Language menu always shows English

### ISSUE THREAD

**Issue by danielfe** [microsoft/community-organization-operations-suite#427]
SUMMARY
You can successfully switch to Spanish and all the strings do change, but when you visit a new page the language menu itself still says English. 

STEPS TO REPRODUCE
- On any signed in page use the language menu in the toolbar to change to spanish
- Click any link to go to another page, or refresh
- Note the language menu

RESULTS
Expected - The toolbar would now say Spanish instead of English, since thats the current language choice. 
Actual - the toolbar says English even though im using HCH in spanish

VIDEO
https://www.loom.com/share/f6c0bf2fe96440b9a5889f9c50794b4e

**Comment by ThomasKapler** [comment]
Interesting - when I try this, the language menu only incorrectly reverts to display "English" when I refresh. Otherwise it displays the correct setting as navigate other pages within the app...
