### ISSUE TITLE
New Service form descriptive text needs updating and corrections  

### ISSUE THREAD

**Issue by ThomasKapler** [microsoft/community-organization-operations-suite#441]
See image below - Notice the very first line: "A service is a succulent set of tasks..." - Succulent?? Is this a joke or error?

Also...under "Data Type" the instructions say: "Change the type of data you would like a field to collect"
should say something like "Set the data type of this field and whether it is optional"

![image](https://user-images.githubusercontent.com/98921014/158208753-21658976-c595-48ee-ba47-b6380968ae9a.png)

**Comment by danielfe** [comment]
Proposed new design and strings

New strings:
* A service is a customizable form. They can be used to capture data for a program offered to clients or for internal purposes.
* Provide a description and instructions to specialists to help them understand the purpose of the service and how to keep data clean.
* Add and remove fields for the data you need. Fields can be text, dates , multiple choice or other types. Fields can be required or optional.

There are also label changes. 


![image](https://user-images.githubusercontent.com/4665144/160906811-3405b6aa-e132-4bce-ae82-60018a973b26.png)
