### ISSUE TITLE
Remove eslint rules about no-deps on `useEffect`

### ISSUE THREAD

**Issue by YohannParis** [microsoft/community-organization-operations-suite#462]

**Comment by karlolsonuc** [comment]
Looking at this, I guess there's a pattern that we should be using to avoid needing to change the eslint rules. Wish it was something demonstrated in the core docs in a more obvious way though: 

https://betterprogramming.pub/why-eslint-hates-your-useeffect-dependencies-react-js-560fcac0b1f

**Comment by YohannParis** [comment]
> Looking at this, I guess there's a pattern that we should be using to avoid needing to change the eslint rules. Wish it was something demonstrated in the core docs in a more obvious way though:
> 
> https://betterprogramming.pub/why-eslint-hates-your-useeffect-dependencies-react-js-560fcac0b1f

@karlolsonuc this is magnificent and a huge learning step toward React Hooks!
Thank you for your due diligence on this issue.
