### ISSUE TITLE
CBO name Misspelled 

### ISSUE THREAD

**Issue by njrosedurhamtry** [microsoft/community-organization-operations-suite#465]
Summary:                  Please be advised that the title T.R.Y. is misspelled. 

Steps to reproduce:  When I log into onboard Healthy Community Hub the title T.R.Y. on the left side of the dashboard it's incorrectly misspelled. 

Results:                     Expected for the typo to be spelled correctly.

Environment Information:   Healthy Community Hub 

Screenshot:
![HCH TRY 1](https://user-images.githubusercontent.com/101285072/159790348-4f7fa1c0-bcfb-4203-8e10-67d140d40cd4.png)
![HCH TRY 2](https://user-images.githubusercontent.com/101285072/159790357-62b14fc0-2d67-43ad-804a-f292371d7871.png)

**Comment by danielfe** [comment]
This is likely in the database but there is no way for users to edit this. In the future we'll add settings for the organization but for now can we please fix this manually? Together for Resilient Youth

**Comment by phorne-uncharted** [comment]
I updated the production & demo databases. Someone else will have to confirm that it now provides the expected result.

**Comment by phorne-uncharted** [comment]
Confirmed fixed on prod.

**Comment by njrosedurhamtry** [comment]
Thank you.
