### ISSUE TITLE
Service forms do not indicate if text or number is required in field - this blocks submission

### ISSUE THREAD

**Issue by ThomasKapler** [microsoft/community-organization-operations-suite#471]
The submit button does not activate for starting service, even though all fields appear to be filled in. This occurs when text is entered in a number filed, but there is no indication that number is required

1. Tested On staging
2. start "complex form" service
3. fill in all fields with text characters

Submit button would not activate because one of the fields requires a number. 
There is no way to tell a number is required, and no warning that text entered is invalid and preventing submission.

The fix here is to alert user that a number is required for number fields. This could be stated in the label, but there should be another indication. 

Also, the editor could prevent text from being entered.

Requires design - e.g. append label with "valid number is required", and display a warning when non-numeric characters are entered

![image](https://user-images.githubusercontent.com/98921014/160084802-e041b59f-0060-478e-8f2d-54cb06e0e764.png)

**Comment by ThomasKapler** [comment]
I figured out the issue - one of the fields requires a number, but there is no way to tell a number is required, or warning that text entered is invalid and preventing submission.

The fix here is to alert user that a number is required. This could be stated in the label, but there should be another indication.

Requires design

**Comment by danielfe** [comment]
Proposed design is to make this part of our existing form validation. If they enter something that isnt a valid number let's let them know with the same UI we'd use to show that a field is required

![image](https://user-images.githubusercontent.com/4665144/160906514-8c549d49-da38-4643-a762-7173df1a6aa2.png)

**Comment by danielfe** [comment]
It seems like it also cant submit if the field is blank! Even if the field is optional. We should bump this up.
