### ISSUE TITLE
Display a loading spinner while data for `Start a Service` side panel is loading 

### ISSUE THREAD

**Issue by jryu01** [microsoft/community-organization-operations-suite#479]
As commented in https://github.com/microsoft/community-organization-operations-suite/issues/342#issuecomment-1081140957, 
Display a loading spinner when data is loading on the Start a Service side panel.

**Comment by ThomasKapler** [comment]
Just thinking about this...It would be nice if you could start a service while the Request are being loaded. e.g. if the request loading takes a long time (e.g. there are hundreds) to load and you just want to start a service...

**Comment by jryu01** [comment]
That’s how the app behaves currently. Services start to load once the side panel is opened triggered by clicking a `Start a service` button and it doesn’t necessarily depend on the loading of the requests. If the requests loading takes a long time, a user can open the side panel and starts the service once services are loaded even though requests are still loading. 

Just note that since there are limits in how many parallel network requests a browser can make, if the browser is busy with loading other resources (especially when you hard refresh on the page and it’s loading all additional resources like js and css files), and services loading is triggered by user action which happens to be later than the initial loading of the page, requests for the services is pushed back to the requests queue (by the browser itself) and sometimes finishes last especially with very slow network connection. But I don’t think this is an issue in the most cases and I think the app just behaves correctly.
