### ISSUE TITLE
Create a link to email support

### ISSUE THREAD

**Issue by danielfe** [microsoft/community-organization-operations-suite#483]
Right now there is no way from the UI to email the support team with feedback

**Comment by danielfe** [comment]
Correction to my original description, you CAN message support from the help thing in the bottom right corner. You can also get to the help content in a separate tab. But both are a little hard to discover. CTT would like to try a more obvious affordance in the navbar, both for emailing support and getting to the help content. As a separate step we should add telemetry and understand what people are actually using. 

Suggested design:
![image](https://user-images.githubusercontent.com/4665144/160902679-36798733-2245-4858-9662-38915ef880f3.png)

**Comment by phorne-uncharted** [comment]
Could you clarify exactly how telemetry should be added? Specifically, which clicks should be tracked and what data should be included.

**Comment by danielfe** [comment]
Thanks Phil, ill file a separate issue for the telemetry where I'll define the events. Im thinking about a "access help" event that has fields for what they accessed (?, contact, or Help content) and which page they were on when the clicked it. But I can write that up.

**Comment by danielfe** [comment]
to clarify behavior here
Let's change the first link to "Help Articles" and have it open http://help.healthycommunityhub.com in another tab
The second "Contact Support" opens an email to help@healthycommunityhub.com
