### ISSUE TITLE
When waiting for data on reporting page it says "no results" instead of loading

### ISSUE THREAD

**Issue by danielfe** [microsoft/community-organization-operations-suite#505]
See video. When I went to look at requests on reporting page it said no results for several seconds before loading data. This is confusing it should show "loading…"

I was able to see this happen once on the tags page too. When fixing this it would be good to do a quick scan to see if this is an issue on multiple pages. 

https://www.loom.com/share/985b3b8bdb7a4e83be870553197b7bdc

**Comment by phorne-uncharted** [comment]
The dashboard tables display the busy spinner along with `loading...` which seems like the best way to show the information to the user.

![image](https://user-images.githubusercontent.com/20339669/168332225-5620a735-233b-4b97-a16f-2920802179bd.png)
