### ISSUE TITLE
"Curamericas" showing in copyright field at bottom of HCH

### ISSUE THREAD

**Issue by IFPHA-Keith** [microsoft/community-organization-operations-suite#510]
"Curamericas" is showing up at the bottom of the HCH page in the copyright field.  This needs to be changed to "Healthy Community Hub" to reduce confusion. Screenshot is below.

![Curamericas change](https://user-images.githubusercontent.com/100182999/162803983-ffd470c1-201f-478f-adc8-1e4168eb8f32.jpg)

**Comment by danielfe** [comment]
@IFPHA-Keith I learned that this is considered correct behavior for now. The azure instance hosting HCH is owned by Curamericas. If HCH wants to change it, it's up to HCH to form or choose a different entity that can host an azure instance and host a privacy policy they can stand behind.

**Comment by IFPHA-Keith** [comment]
Understood. I will pass that information along.  Thank you! Closing the issue, for now.
