### ISSUE TITLE
Click to exit specialist details from Specialist tab return user to Dashboard Tab

### ISSUE THREAD

**Issue by ThomasKapler** [microsoft/community-organization-operations-suite#526]
See attached Video.

1. Go to the Specialist tab
2. Click a specialist name to see detail is side panel
3. click on the specialists list to close the details view and return to specialists tab

You will be kicked out of Specialists tab and return to the Dashboards page
![Does not return to same page 18apr2022](https://user-images.githubusercontent.com/98921014/163819607-d8be03c2-ea42-40a6-a8f0-8366051dd7a3.gif)

**Comment by karlolsonuc** [comment]
Getting repro on my local, and not just with the specialist tab, but also with the clients tab. It appears to be an issue with the navigate.ts util using history.path and not history.pathname as expected. Should be a one line fix.
