### ISSUE TITLE
Offline Mode: Retain Previously Read Records

### ISSUE THREAD

**Issue by phorne-uncharted** [microsoft/community-organization-operations-suite#534]
When the system is in offline mode, it should still display previously read records. If the user navigates to different pages, whatever had previously been read for those pages needs to be displayed.

However the data gets stored for the client, the system needs to be able to encrypt it (eventually). It is not a requirements right now to encrypt it, but the chosen approach needs to support encryption.

- [x] Create a Service Worker to handle cache
- [x] Keep a local copy (cache) of the GraphQL request?
- [x] Disable unavailable actions when offline

**Comment by phorne-uncharted** [comment]
To add more context to the caching of data, no entity that has private information will be cached. This means that requests, service entries, specialists and clients will not be stored locally. Any other data can be cached.

**Comment by danielfe** [comment]
Thanks for the clarification Phil. Indeed, the only data that should be shown is the data that was already in memory or was "painted" on the screen. We don't need to intentionally keep read data around. It's better to replace a table of data with a "you are offline" message than store private data locally.
