### ISSUE TITLE
If client is created from a service flow, automatically select that client after creation

### ISSUE THREAD

**Issue by danielfe** [microsoft/community-organization-operations-suite#556]
Currently if you are entering data into a service form and add a new client, when you finish creating the client and the sheet dismisses you have to then select that client as a second step. We should automatically choose that client from the pulldown. 

![image](https://user-images.githubusercontent.com/4665144/166542993-f1053efc-d0c3-4c63-9441-05af7556313c.png)

**Comment by danielfe** [comment]
Related to  #484 , which is about refilling the new client form from a name the user may have started typing in the client search field.

**Comment by mdeitner** [comment]
This work was completed on #484
