### ISSUE TITLE
Kiosk Mode: Form Entry Service Selection

### ISSUE THREAD

**Issue by phorne-uncharted** [microsoft/community-organization-operations-suite#573]
From the kiosk mode service form entry page, the user should be able to navigate to the kiosk mode service list page regardless of how the user got to the form entry page. This is to be achieved by having a link at the top of the page to navigate to the service list page.

![image](https://user-images.githubusercontent.com/20339669/167665396-1435181b-cae8-4bad-b960-2287e00312ab.png)

**Comment by mdeitner** [comment]
The work for this issue was done on #572
