### ISSUE TITLE
Telemetry: "Filters Applied" is always true on "Data Exported" event

### ISSUE THREAD

**Issue by danielfe** [microsoft/community-organization-operations-suite#654]
When the Data Exported event is fired on the reporting page, it seems that the custom field of "Filters Applied" is always true. 

By default the table is sorted by one of the columns, so maybe that is what's counted as an applied filter?

STEPS TO REPRODUCE
- log in
- go to reporting
- Don't touch any filters, just hit print or export data
- Look at the data in azure

RESULTS
Expected: Filters Applied is false since I didnt apply any
Actual: Filters Applied is true.

**Comment by YohannParis** [comment]
Hello @danielfe,

I'm not sure if this is wrong, as by default we have filters applied on Reporting, if you click on `Show Fields` button, you will see that not all is exported/print, but a selected list of columns.

Those selected columns are _filters_.

Do you want to ignore the base state of filtering for the `Filters Applied` field value to be set to `false` until a user modify it?

**Comment by danielfe** [comment]
Makes sense, thank you for the explanation. Im not sure we have time for this, which is fine, but I think in this case filters should be true if the user put a filter on a column. It should ignore which columns are hidden/shown. As a backup plan I like your suggestion of ignoring the default set of hidden/shown columns. Thank you.
